### PR TITLE
Producing multiple html files from one template

### PR DESCRIPTION
**Pull request by deni35**
I'm doing something kinda a static blog and I need to produce a several pages from one template.
I change a little your package and now I can do it the next way:
```
.pipe(handlebars(data, {
   pages: {
      'my-page.handlebars' : ['my-page.html', 'my-page-2.html', 'my-page-3.html']
   },
   helpers: gulp.src(config.src.helpers),
   partials: gulp.src(config.src.includes)
}))
```
In package I take this property:
```var pages = options.pages[ parsedPath.base ];```
And do a loop in which I generate html files from compiled template:
```
      var tpl = Handlebars.compile(file.contents.toString());

      if( pages == null ) {
        data._file = file;
        file.contents = new Buffer(tpl(data));
        self.push(file);
      } else {
        pages.forEach(function (pageName, i) {
          var pageFile = file.clone();
          parsedPath.base = pageName;
          pageFile.path = path.format(parsedPath);
          data._pageNum = i;
          data._file = pageFile;

          pageFile.contents = new Buffer(tpl(data));
          self.push(pageFile);
        });
      }
```

### CODE REVIEW

**Comment by deni35** [comment]
Also maybe would be good if you add function which produce copies.

```javascript
function copy(count) {
    return through.obj(function (file, enc, callback) {
        if (file.isNull()) {
            return callback(null, file);
        }
        if (file.isStream()) {
            return this.emit("error", "Streaming not supported");
        }

        for (var i = 1; i <= count; i++) {
            var page = file.clone();
            var _path = path.parse(page.path);
            _path.name += "-" + i;
            _path.base = _path.name + _path.ext;
            page.path = path.format(_path);

            page.pageNum = i-1;
            this.push(page);
        }

        callback();
    });
}
```

**Comment by deni35** [comment]
Request has been updated.

**Comment by TakenPilot** [comment]
That's neat.  Thanks!

**The Coverage:**  It's useful to write tests to prove your code works.  It seems neither branch in your new if statement is being tested:  https://coveralls.io/builds/4589404/source?filename=index.js#L124

**The Idea:**  
I think `pages` is doing the same thing as `data`, i.e., 
```js
gulp.src('./app/index.hbs')
      .pipe(handlebars({contents:"whatever"}, // < -- data
      {
        helpers: gulp.src('./app/helpers/**/*.js'),
        partials: gulp.src('./app/partials/**/*.hbs')
      }))
      .pipe(gulp.dest('./dist'));
```
but I think I like your format better.

I'm often using the `data/pages` parameter to pass in promises or streams from a file or a database like this:

```js
gulp.src('./test/fixtures/test-data.html')
        .pipe(handlebars(promiseFromFile)) // or streamFromFS
        .on('error', function (err) {
          done(err);
        })
        .on('data', function (data) {
          expect(data.contents.toString()).to.equal(expectedContents);
          done();
        });
```

I guess the main question for this new functionality is: if multiple templates are being passed in from gulp, what do you expect the multiple pages to do?

**Comment by deni35** [comment]
See my project https://bitbucket.org/dddenisss/static-gallery-demo/overview
See: gulpfile.js/tasks/handlebars-compiler.js
and
gulpfile.js/template-data.js/gallery/content function which returns content array depending on data._pageNum.

Maybe 'page' isn't the best name for this options.Think up something another.

**Comment by TakenPilot** [comment]
I think, based on the project that you referenced, that there are many different ways to use handlebars to generate static content.

Case 1)  Multiple templates with the same data.  Multiple templates come from gulp.
Case 2)  A single template with different data.  Different data come from gulp.
Case 3)  Multiple templates with different data.  Which comes from gulp???

Right now this project handles the first case.  I'm using it to pull the site titles, blog posts, headers and footers from google spreadsheets and google docs that a client is editing.

You're trying to handle the second case or third case, I think, but I'm not sure.

If you're just trying to put lots of different data into lots of different templates, I don't really see any need to use gulp to stream anything at all.

**Comment by deni35** [comment]
I did something kinda your first case.
I selected my template:
```
.pipe(_if('**/news.handlebars', copy(data.pageCount)))
```
And I made a few copies:

```
function copy(count) {
    return through.obj(function(file, enc, callback) {
        if (file.isNull()) {
            return callback(null, file);
        }
        if (file.isStream()) {
            return this.emit("error", "Streaming not supported");
        }

        for (var i = 1; i <= count; i++) {
            var page = i == 1 ? file : file.clone();
            if(i > 1) page.path = addSuffix(page.path, "-" + i);

            page.pageNum = i;
            this.push(page);
        }

        callback();
    });
}
```

But I needed to know which file is being currently compiling. For this I saved a reference on current file into the data: https://github.com/deni35/gulp-static-handlebars/commit/632d75d915a097eb8e3108e249efa6ffc3def827

Then I came up with a completely new method and fully change request.
My new method allows to compile template only one time and produce many html files.

How your method works I can't understand.

**Comment by TakenPilot** [comment]
That's pretty good.

I think if we're adding new functionality in a completely new way, it might make sense to just make a new npm module.

**Comment by TakenPilot** [comment]
Closing, with the idea that if the base functionality of the module is different, we should just fork the project and give it a new name instead.

**Pull request closed without merging**
